### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by kikieri** [billcccheng/instagram-terminal-news-feed#25]
got this error:

Traceback (most recent call last):
  File "/Users/kalucci/Downloads/instagram-terminal-news-feed/start.py", line 122, in <module>
    main()
  File "/Users/kalucci/Downloads/instagram-terminal-news-feed/start.py", line 115, in main
    session = login(credential)
  File "/Users/kalucci/Downloads/instagram-terminal-news-feed/start.py", line 96, in login
    session, res = get_login_session({'username': user, 'password': pwd})
  File "/Users/kalucci/Downloads/instagram-terminal-news-feed/start.py", line 73, in get_login_session
    session.headers.update({'X-CSRFToken': req.cookies['csrftoken']})
  File "/usr/local/lib/python3.9/site-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.9/site-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by donwany** [comment]
getting the same errors
